name: Show Calling Context
description: Prints GitHub contexts for debugging
runs:
  using: composite
  steps:
  - name: Show Information
    shell: bash
    run: |
      env | grep -v TOKEN | grep GITHUB | sed -e 's/=/ = /g' | column -t

  - name: Show GitHub Context
    uses: actions/github-script@v7
    with:
      script: |
        console.log('hello, world!');
