name: Combines Secrets
description: |
  Combines first-secret and second-secret into a file.
inputs:
  first-secret:
    required: true
  second-secret:
    required: true
  to-file:
    description: Where to write the comnbined secret. Should be a filename.
    default: "/tmp/combined-secret"
    required: false
outputs:
  combined-file-path:
    description: Where it was written. The full path.
    value: ${{ steps.return-full-path.outputs.fullpath }}
runs:
  using: composite
  steps:
  - name: Write combined secret
    id: combine-and-write
    shell: bash
    run: |
      echo -en "${{ inputs.first-secret }}\n${{ inputs.second-secret }}" >> "${{ inputs.to-file }}
      
  - name: Return full path
    id: return-full-path
    shell: bash
    run: |
      set -eo pipefail
      echo "fullpath=$(realpath ${{ inputs.to-file }})" | tee -a $GITHUB_OUTPUT
