name: Workflow Dispatch Debug

on: 
  workflow_dispatch:

jobs:
  debugwd:
    name: debug-workflow-dispatch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: debug info from calling workflow
        run: |
          echo -e $(env | grep -v TOKEN | grep GITHUB | sed -e 's/=/ = /g') | column -t
      - name: debug info from composite
        uses: ./.github/actions/debugging
        
