name: Debug

on: 
  workflow_dispatch:
  pull_request:
  pull_request_target:
  push:

jobs:
  debugwd:
    name: debug-workflow-dispatch
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: debug info from calling workflow
        run: |
          env | grep -v TOKEN | grep GITHUB | sed -e 's/=/ = /g' | column -t
      - name: debug info from composite
        uses: ./.github/actions/debugging
        
