# This workflow generates the JSON representation
name: Generate Package Locks

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  generate-package-locks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install PyYAML
      - name: Generate lock file JSON from existing directory structure
        id: generate-package-locks
        run: |
          set -o pipefail
          python scripts/packagemapping/packagemapping.py | tee /tmp/packagelocks.json
          base64 -w 0 /tmp/packagelocks.json | tee /tmp/packagelocks.json.b64
          echo "package_locks_b64=$(cat /tmp/packagelocks.json.b64)" >> $GITHUB_OUTPUT
      - name: Decode and display lockfile JSON (Sanity Check)
        run: |
          set -o pipefail
          test -n "${{ steps.generate-package-locks.outputs.package_locks_b64 }}" \
            || { echo "::error::output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
          echo ${{ steps.generate-package-locks.outputs.package_locks_b64 }} | base64 -d | jq \
            || { echo "::error::output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
