# This workflow generates the JSON representation
name: Generate Package Locks

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  generate-package-locks:
    outputs:
      package_locks_b64: ${{ steps.generate-package-locks.outputs.package_locks_b64 }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: |
          pip install PyYAML
      - name: Generate lock file JSON from existing charts
        id: generate-package-locks
        run: |
          set -o pipefail
          python scripts/packagemapping/packagemapping.py | tee /tmp/packagelocks.json
          base64 -w 0 /tmp/packagelocks.json | tee /tmp/packagelocks.json.b64
          echo "package_locks_b64=$(cat /tmp/packagelocks.json.b64)" >> $GITHUB_OUTPUT
      - name: Decode and display lockfile JSON (Sanity Check)
        run: |
          set -o pipefail
          test -n "${{ steps.generate-package-locks.outputs.package_locks_b64 }}" \
            || { echo "::error::output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
          echo ${{ steps.generate-package-locks.outputs.package_locks_b64 }} | base64 -d | jq \
            || { echo "::error::output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
  
  compare-package-lock-manifests:
    needs: generate-package-locks
    outputs:
      needs-updating: ${{ steps.compare-package-locks.outputs.needs-updating }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine if package lock entries need updating
        id: compare-package-locks
        run: |
          needsupdating=false
          wget https://komish.github.io/actions-workflow-call-test/lock.json -O current-locks.json
          set -o pipefail
          test -n "${{ needs.generate-package-locks.outputs.package_locks_b64 }}" \
            || { echo "::error::output package_locks_b64 did not contain base64 content generated from the previous step"; exit 2 ;}
          echo ${{ needs.generate-package-locks.outputs.package_locks_b64 }} | base64 -d | jq > generated-locks.json \
            || { echo "::error::output package_locks_b64 did not contain valid JSON once decoded" ; exit 3 ;}
          jq .packages current-locks.json > current-packages.json
          jq .packages generated-locks.json > generated-packages.json
          diff current-packages.json generated-packages.json || needsupdating=true
          echo needs-updating=${needsupdating} >> $GITHUB_OUTPUT

  read-needs-updating-result:
    needs: compare-package-lock-manifests
    runs-on: ubuntu-latest
    steps:
      - run: echo "update required - ${{ needs.compare-package-lock-manifests.outputs.needs-updating }}"

  craft-pr-to-project:
    needs: compare-package-lock-manifests
    if: ${{ needs.compare-package-lock-manifests.outputs.needs-updating }} == "true"
    runs-on: ubuntu-latest
    steps:
      - run: echo "It ran!"

          
        