name: secret-access-testing

on:
  workflow_dispatch:
  pull_request:
    branches: ["*"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "${{ secrets.SUPER_SECRETE_B64 }}"
        echo "${{ secrets.SUPER_SECRETE_B64 }}" | base64 -d

    - name: test demo
      run: |
        echo -en "${{ secrets.DEMO_CERT_2 }}" > /tmp/demo.crt
        echo -en "${{ secrets.DEMO_PRIVKEY_2 }}" > /tmp/demo.key
        md5sum *.crt *.key
        curl -s \
         -X GET \
         --cert /tmp/demo.crt \
         --key /tmp/demo.key \
         --pass '${{ secrets.PEM_PASS }}' \
         -H 'accept: application/json' \
         'https://${{ secrets.API_HOST }}/v1/tools'
