name: Test OpenShift Tools Installer

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install chart-verifier
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          skip_cache: true
          chart-verifier: 0.1.0
          
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
