name: Test OpenShift Tools Installer

on:
  workflow_dispatch:

jobs:
  install-cv-ubuntu-latest-1-11:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install chart-verifier
        uses: redhat-actions/openshift-tools-installer@v1.11
        with:
          source: github
          skip_cache: true
          chart-verifier: 0.1.0
          

  install-oc-ubuntu-latest-1-11:
    runs-on: ubuntu-22.04
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1.11
        with:
          oc: latest
          skip_cache: true

  install-cv-ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install chart-verifier
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          skip_cache: false
          chart-verifier: 0.1.0
          

  install-oc-ubuntu-latest:
    runs-on: ubuntu-22.04
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
          skip_cache: false

  install-cv-ubuntu-2404:
    runs-on: ubuntu-22.04
    steps:
      - name: Install chart-verifier
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          source: github
          skip_cache: true
          chart-verifier: 0.1.0
          

  install-oc-ubuntu-2404:
    runs-on: ubuntu-22.04
    steps:
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest
          skip_cache: true
