name: Test OpenShift Tools Installer

on:
  push

jobs:
  install-tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tool: [cv, oc]
        version: [v1.11, v1]
    steps:
      - uses: actions/setup-node@v4
        if: ${{ matrix.tool == 'cv' }}
        with:
          node-version: '16'
      - name: Set version
        id: set_version
        run: echo "VERSION=${{ matrix.version }}" >> $GITHUB_ENV
      - name: Install tools
        uses: redhat-actions/openshift-tools-installer@v${{ env.VERSION }}
        with:
          source: github
          skip_cache: false
          chart-verifier: ${{ matrix.tool == 'cv' && '0.1.0' || '' }}
          oc: ${{ matrix.tool == 'oc' && 'latest' || '' }}
